# Dockerfile
FROM node:18-alpine

# 建立 app 目錄
WORKDIR /app

# 複製 package 資料並安裝依賴
COPY package*.json ./
RUN npm install

# 複製所有程式碼
COPY . .

# 預設對外開啟的 port
ENV PORT=3000
EXPOSE 3000

# 開發環境使用 start:dev
CMD ["npm", "run", "start:dev"]